theBudgetApp/config/routes.rb
Rails.application.routes.draw do

  TheBudgetApp::Application.routes.draw do
    resources :users
    root :to => redirect('/users')
    
    resources :home
  end
end

theBudgetApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

theBudgetApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
    end
    
    def create
    @users = Users/create!()
    end 
end

theBudgetApp/app/helpers/application_helper.rb
module ApplicationHelper
end

theBudgetApp/app/views/layouts/application.html.haml
%html
  %head
    %title budgetApp!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
  = yield

theBudgetApp/app/views/users/about.html.haml
%div#header
    %h1#appName login
    
%body
    %p Smart Budget is an web application created solely for students like you!!<br>
       College in itself is hectic, taking care of your budget on top of that can be stressful. <br>



    

theBudgetApp/app/views/users/help.html.haml
%h2 help

theBudgetApp/app/views/users/index.html.haml
%div#header
    %h1#appName Smart Budget
    %button.alert#b1 HELP
    %button.alert#b1 LogIn
    
    
%body#thebody
%table
    %tr
        %th#siteInfo ABOUT US
        %th#signUp SIGN UP
    %tr 
        %td#addspace 
            %p This app is to help students to manage their budget.<br>Saving saves students and this app helps student to<br> save their money by keeping track of their expendture.
        %td#addspace 
            %p This app is designed for students.<br>You can sign up for free with your .edu email.<br>Hurry up and start your budgeting today!
    %tr
        %td#tocenter= link_to "Learn More", home_index_path
        %td#tocenter= link_to "Create new account", new_user_path
    %tr
        %td#tocenter
            %button.alert#b2 CLICK HERE
        %td#tocenter
            %button.alert#b2 CREATE ACCOUNT
        
%footer
    %p#atend &copy; 2016 Sunny Shrestha, Safath Zaman, Jyoti Rana, Mira Sainju, Bradley Kunz All Rights Reserved

theBudgetApp/app/views/users/login.html.haml
%h2 Login

= form_tag home_path(@home), :method => :get do
    = label "Username"
    = text_field
    
    = label "Password"
    = password_field
    
<<<<<<< HEAD
    = submit_tag 'Submit'
=======
    = submit_tag 'Submit'
>>>>>>> f208b0de6a9dc8c2c8e5623813562cff337936ed

theBudgetApp/app/views/users/new.html.haml
%div#header
    %h1#appName Sign Up
    
= form_tag users_path, :method => :post do

    = label :users, :fname, 'First Name'
    = text_field :users, :fname
    
    = label :users, :lname, 'Last Name'
    = text_field :users, :lname    
    
    = label :users, :email, 'Email Address'
    = text_field :users, :email   
    
    = label :users, :username, 'Username'
    = text_field :users, :username  

    = label :users, :username, 'Password'
    = text_field :users, :password     
    
    = submit_tag 'Save Changes'
<<<<<<< HEAD
    
=======
    
>>>>>>> f208b0de6a9dc8c2c8e5623813562cff337936ed